// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CSharpToTypeScript
{
    internal sealed partial class Vsix
    {
        public const string Id = "CSharpToTypeScript.95c0dd1a-0be9-4027-a4c8-3e58659d3c35";
        public const string Name = "CSharpToTypeScript";
        public const string Description = @"Generate Typescript code from a C# class definition.";
        public const string Language = "en-US";
        public const string Version = "1.0.0.4";
        public const string Author = "Programount Inc.";
        public const string Tags = "TypeScript, C#, schema, validation";
    }
}
