// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CSharpToTypeScript
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string CSharpToTypeScriptPackageString = "6b09e960-199a-4025-9920-d2355ce65333";
        public static Guid CSharpToTypeScriptPackage = new Guid(CSharpToTypeScriptPackageString);

        public const string CSharpToTypeScriptGroupString = "b060fb8f-7d33-4ce1-b645-968be8e80811";
        public static Guid CSharpToTypeScriptGroup = new Guid(CSharpToTypeScriptGroupString);

        public const string GenerateTypeScriptCommandString = "133c2224-68d4-4b27-85bb-e19d8bb1da7d";
        public static Guid GenerateTypeScriptCommand = new Guid(GenerateTypeScriptCommandString);

        public const string GenerateTypeScriptCommandIconString = "4768922b-48c6-4c55-9bae-03dd8b34a9af";
        public static Guid GenerateTypeScriptCommandIcon = new Guid(GenerateTypeScriptCommandIconString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int CSharpToTypeScriptGroupID = 0x0001;
        public const int GenerateTypeScriptCommandID = 0x0100;
        public const int GenerateTypeScriptCommandIconID = 0x0001;
    }
}