// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CSharpToTypeScript
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string CSharpToTypeScriptPackageString = "6b09e960-199a-4025-9920-d2355ce65333";
        public static Guid CSharpToTypeScriptPackage = new Guid(CSharpToTypeScriptPackageString);

        public const string CSharpToTypeScriptGroupString = "b060fb8f-7d33-4ce1-b645-968be8e80811";
        public static Guid CSharpToTypeScriptGroup = new Guid(CSharpToTypeScriptGroupString);

        public const string GenerateTypeScriptCommandString = "133c2224-68d4-4b27-85bb-e19d8bb1da7d";
        public static Guid GenerateTypeScriptCommand = new Guid(GenerateTypeScriptCommandString);

        public const string CSharpToTypeScriptIconsString = "d10a7af3-ab4a-479a-a319-42083237cab7";
        public static Guid CSharpToTypeScriptIcons = new Guid(CSharpToTypeScriptIconsString);

        public const string GenerateReactFormResolverCommandString = "775109eb-85cc-473f-8d2f-32837b114ba6";
        public static Guid GenerateReactFormResolverCommand = new Guid(GenerateReactFormResolverCommandString);

        public const string GenerateReactstrapFormCommandString = "255420d4-9cac-40a5-9281-2e4097233679";
        public static Guid GenerateReactstrapFormCommand = new Guid(GenerateReactstrapFormCommandString);

        public const string GenerateVuelidateRulesCommandString = "eaf2e89b-99fd-4988-8f17-33c12615b99e";
        public static Guid GenerateVuelidateCommand = new Guid(GenerateVuelidateRulesCommandString);

        public const string GenerateVueFormCommandString = "888f23a9-4d3c-457a-97f3-fcd97117eea0";
        public static Guid GenerateVueFormCommand = new Guid(GenerateVueFormCommandString);

        public const string CSharpEditorContextString = "d9d1b00b-46d3-4686-a211-b964aa334e0e";
        public static Guid CSharpEditorContext = new Guid(CSharpEditorContextString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int CSharpToTypeScriptGroupID = 0x0001;
        public const int GenerateTypeScriptCommandID = 0x0100;
        public const int GenerateReactFormResolverIconID = 0x0001;
        public const int GenerateReactstrapFormIconID = 0x0002;
        public const int GenerateVuelidateRulesIconID = 0x0004;
        public const int GenerateVueFormIconID = 0x0003;
        public const int GenerateReactFormResolverCommandID = 0x0101;
        public const int GenerateReactstrapFormCommandID = 0x0102;
        public const int GenerateVuelidateRulesCommandID = 0x0103;
        public const int GenerateVueFormCommandID = 0x0104;
    }
}